{"name": "test_01_spd[test_data0]", "status": "broken", "statusDetails": {"message": "IndexError: Replacement index 2 out of range for positional args tuple", "trace": "self = <cluster_autotest.testcases.a8e.test_a8e_panel.TestUint_Panel object at 0x0000024DFFE85340>\ntest_data = {'adb_pull_dest': './testdata/actual/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'android_log_path': '/mnt/user/log_android/', 'cfg_path': 'E:/工作文档\\\\学习文档/自动化/cluster_autotest/common/canoe_project/Configuration.cfg', ...}\n\n    @execut_failed_cases.execut_failed_cases\n    @pytest.mark.parametrize(\"test_data\", [read_yaml.read_yaml('./config/config.yaml')])\n    def test_01_spd(self,test_data):\n        app = CANoe() #定义CANoe为app\n        app.open_cfg(test_data[\"cfg_path\"]) #导入某个CANoe congif\n        time.sleep(2)\n        app.start_Measurement()\n        time.sleep(3)\n        test_qnx = qnx(test_data[\"devices\"],test_data[\"qnx_ip\"],test_data[\"qnx_user\"],test_data[\"qnx_passwd\"])\n        test_qnx.qnx_screenshot(test_data[\"qnx_screenshot_path\"])\n        test = adb.adb_pull_image(test_data[\"devices\"],\n                                        test_data[\"adb_pull_source\"],\n                                        test_data[\"adb_pull_dest\"])\n        test_image=Images()\n        test_result = test_image.compare_by_matrix_in_same_area(\n                                                                test_data[\"input_images_path_spd\"],\n                                                                test,\n                                                                test_data[\"image_position_spd\"])\n        allure.attach.file(test_data[\"input_images_path_spd\"], name=\"预期结果\", attachment_type=allure.attachment_type.BMP)\n        allure.attach.file(test, name=\"实际结果\", attachment_type=allure.attachment_type.BMP)\n        app.close_cfg()\n>       assert test_result == None\nE       assert (0, 238, 1, 239) == None\n\ntestcases\\a8e\\test_a8e_panel.py:37: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nargs = (<cluster_autotest.testcases.a8e.test_a8e_panel.TestUint_Panel object at 0x0000024DFFE85340>,)\nkwargs = {'test_data': {'adb_pull_dest': './testdata/actual/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'androi.../mnt/user/log_android/', 'cfg_path': 'E:/工作文档\\\\学习文档/自动化/cluster_autotest/common/canoe_project/Configuration.cfg', ...}}\ntest_name = 'test_01_spd', current_time = datetime.datetime(2024, 3, 11, 17, 19, 10, 749196), formatted_time = '20240311-171910'\nlocal_path = './logs/test_01_spd20240311-171910'\n\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        \"\"\"\n        用于捕获AssertionError异常\n        \"\"\"\n        try:\n            func(*args, **kwargs) # 执行测试用例\n        except AssertionError:\n            test_name = func.__name__  # 获取测试用例名称\n            current_time = datetime.now()\n            formatted_time = current_time.strftime(\"%Y%m%d-%H%M%S\")\n            local_path = './logs/' + test_name + formatted_time\n            os.mkdir(local_path)\n>           export_android_log(local_path)\n\ntestcases\\execut_failed_cases.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntestcases\\execut_failed_cases.py:39: in export_android_log\n    adb.adb_root(devices)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndevices = '192.168.7.16:5555'\n\n    @staticmethod\n    def adb_root(devices:str):\n        \"\"\"\n        导出安卓文件\n        parame: devices: 设备地址通过adb devices获得\n        \"\"\"\n        try:\n            command = \"adb -s {} root\".format(devices)\n            process = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)\n            process.stdin.close()\n            process.wait()\n            status_code=process.returncode  #执行状态码，为0表示执行成功，为1表示执行失败\n            #cmd_result=process.communicate() #以元组的形式返回执行命令的输出\n>           logger.info(\"{}执行成功,执行状态码为{},命令输出为{}\".format(command,status_code))\nE           IndexError: Replacement index 2 out of range for positional args tuple\n\ncommon\\adb.py:22: IndexError"}, "attachments": [{"name": "预期结果", "source": "eba7a6f2-9cb4-481d-9705-5ea1a2ba062e-attachment.bmp", "type": "image/bmp"}, {"name": "实际结果", "source": "7e928183-1009-4737-845f-89e7adffee1f-attachment.bmp", "type": "image/bmp"}], "parameters": [{"name": "test_data", "value": "{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'input_images_path_spd': './testdata/expect/screenshot_spd.bmp', 'input_images_path_eps': './testdata/expect/screenshot_eps.bmp', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './testdata/actual/', 'image_position_spd': [818, 245, 1092, 485], 'image_position_eps': [711, 24, 1227, 80], 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': 'E:/工作文档\\\\学习文档/自动化/cluster_autotest/common/canoe_project/Configuration.cfg', 'dbc_path': './common/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc'}"}], "start": 1710148716786, "stop": 1710148750910, "uuid": "2400813c-0e42-45dc-b609-718eeb580954", "historyId": "3ccbc2ace8d47551058dfb8b20b83d34", "testCaseId": "21d68c7d7fc18b7da512aa878aae7271", "fullName": "testcases.a8e.test_a8e_panel.TestUint_Panel#test_01_spd", "labels": [{"name": "parentSuite", "value": "testcases.a8e"}, {"name": "suite", "value": "test_a8e_panel"}, {"name": "subSuite", "value": "TestUint_Panel"}, {"name": "host", "value": "test-1"}, {"name": "thread", "value": "21800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.a8e.test_a8e_panel"}]}